%global enable64 no
%global atlasblaslib -ltatlas
%global atlaslapacklib -ltatlas

# From src/version.h:#define OCTAVE_API_VERSION
%global octave_api api-v50+

Name: octave	
Version: 4.0.0	
Release: 1
Summary: A high-level interpreted language primarily intended for numerical computations.	

License: GPLv2	
URL: http://www.gnu.org/software/octave/	
Source0: ftp://ftp.gnu.org/gnu/octave/octave-4.0.0.tar.xz

# RPM macros for helping to build Octave packages
Source1:        macros.octave
# Fix to allow pkg build to use a directory
# https://savannah.gnu.org/bugs/?func=detailitem&item_id=32839
Patch0:         octave-pkgbuilddir.patch

BuildRequires:  arpack-devel
BuildRequires:  atlas-devel
BuildRequires:  bison
BuildRequires:  curl-devel
BuildRequires:  desktop-file-utils
BuildRequires:  fftw-devel
BuildRequires:  flex
BuildRequires:  fltk-devel
BuildRequires:  ftgl-devel
BuildRequires:  gcc-gfortran
BuildRequires:  ghostscript
BuildRequires:  gl2ps-devel
BuildRequires:  glpk-devel
BuildRequires:  gnuplot
BuildRequires:  gperf
BuildRequires:  hdf5-devel
#BuildRequires:  GraphicsMagick-c++-devel
#BuildRequires:  java-devel
#BuildRequires:  llvm-devel
#BuildRequires:  suitesparse-devel
BuildRequires:  less
BuildRequires:  libX11-devel
BuildRequires:  mesa-libGL-devel
BuildRequires:  mesa-libGLU-devel
BuildRequires:  mesa-libOSMesa-devel
BuildRequires:  ncurses-devel
BuildRequires:  pcre-devel
BuildRequires:  qhull-devel
BuildRequires:  qrupdate-devel
BuildRequires:  qscintilla-devel
BuildRequires:  readline-devel
BuildRequires: gnuplot
BuildRequires: openjdk
BuildRequires: gcc gcc-gfortran libgomp glibc-devel

Requires: gnuplot openjdk less hdf5
Requires: texinfo info

Requires(post):  info
Requires(preun): info

%description
GNU Octave is a high-level interpreted language, primarily intended for numerical computations. It provides capabilities for the numerical solution of linear and nonlinear problems, and for performing other numerical experiments. It also provides extensive graphics capabilities for data visualization and manipulation. Octave is normally used through its interactive command line interface, but it can also be used to write non-interactive programs. The Octave language is quite similar to Matlab so that most programs are easily portable. 

%package devel
Summary:        Development headers and files for Octave
Group:          Development/Libraries
Requires:       %{name} = %{version}-%{release}
Requires:       readline-devel fftw-devel hdf5-devel zlib-devel
Requires:       atlas-devel gcc gcc-gfortran

%description devel
The octave-devel package contains files needed for developing
applications which use GNU Octave.


%package doc
Summary:        Documentation for Octave
Group:          Documentation
BuildArch:      noarch

%description doc
This package contains documentation for Octave.

%prep
%setup -q
%patch0 -p1 -b .pkgbuilddir

find -name \*.h -o -name \*.cc | xargs sed -i -e 's/<config.h>/"config.h"/' -e 's/<base-list.h>/"base-list.h"/'

# Check permissions
find -name *.cc -exec chmod 644 {} \;


%build
export F77=gfortran
%configure \
	--enable-shared \
	--disable-static \
	--enable-64=no \
 	--enable-float-truncate \
 	--with-blas="-L%{_libdir}/atlas %{atlasblaslib}" \
 	--with-lapack="-L%{_libdir}/atlas %{atlaslapacklib}" \
 	--with-qrupdate \
 	--with-amd \
	--with-umfpack \
	--with-colamd \
	--with-ccolamd \
	--with-cholmod \
 	--disable-jit \
	--with-curl \
	--with-sndfile \
	--enable-gui \
	--with-OSMesa \
	--with-fltk \
	--with-openssl \
	--with-java-homedir=/usr/lib/jvm/openjdk8 \
	--with-x \
	--with-z \
	--disable-docs

# Check that octave_api is set correctly (autogenerated file)
make -C libinterp version.h
if ! grep -q '^#define OCTAVE_API_VERSION "%{octave_api}"' libinterp/version.h
then
  echo "octave_api variable in spec does not match libinterp/version.h"
  exit 1
fi

make %{?_smp_mflags}

%install
make install DESTDIR=%{buildroot}
# Docs - In case we didn't build them and to explicitly install pre-built docs
make -C doc install-data install-html DESTDIR=%{buildroot}

mkdir -p %{buildroot}%{_pkgdocdir}
cp -ar AUTHORS BUGS ChangeLog examples NEWS README %{buildroot}%{_pkgdocdir}/
cp -a doc/refcard/*.pdf %{buildroot}%{_pkgdocdir}/
cp -a doc/interpreter/octave.pdf %{buildroot}%{_pkgdocdir}/
cp -a doc/liboctave/liboctave.pdf  %{buildroot}%{_pkgdocdir}/

#we have to ship infos, the gui requires it.
rm -rf %{buildroot}%{_infodir}/dir

# Make library links
mkdir -p %{buildroot}%{_sysconfdir}/ld.so.conf.d
echo "%{_libdir}/octave/%{version}" > %{buildroot}%{_sysconfdir}/ld.so.conf.d/octave-%{_arch}.conf

# Remove RPM_BUILD_ROOT from ls-R files
perl -pi -e "s,%{buildroot},," %{buildroot}%{_libdir}/%{name}/ls-R
perl -pi -e "s,%{buildroot},," %{buildroot}%{_datadir}/%{name}/ls-R
# Make sure ls-R exists
touch %{buildroot}%{_datadir}/%{name}/ls-R

desktop-file-validate %{buildroot}%{_datadir}/applications/www.octave.org-octave.desktop

# Create directories for add-on packages
HOST_TYPE=`%{buildroot}%{_bindir}/octave-config -p CANONICAL_HOST_TYPE`
mkdir -p %{buildroot}%{_libdir}/%{name}/site/oct/%{octave_api}/$HOST_TYPE
mkdir -p %{buildroot}%{_libdir}/%{name}/site/oct/$HOST_TYPE
mkdir -p %{buildroot}%{_datadir}/%{name}/packages
mkdir -p %{buildroot}%{_libdir}/%{name}/packages
touch %{buildroot}%{_datadir}/%{name}/octave_packages


# rpm macros
mkdir -p %{buildroot}%{_rpmconfigdir}/macros.d
install -m 0644 %SOURCE1 %{buildroot}%{_rpmconfigdir}/macros.d

%post
/sbin/ldconfig
/bin/touch --no-create %{_datadir}/icons/hicolor &>/dev/null || :
/sbin/install-info --info-dir=%{_infodir} --section="Programming" \
        %{_infodir}/octave.info || :

%preun
if [ "$1" = "0" ]; then
   /sbin/install-info --delete --info-dir=%{_infodir} %{_infodir}/octave.info || :
fi

%postun
/sbin/ldconfig
if [ $1 -eq 0 ] ; then
    /bin/touch --no-create %{_datadir}/icons/hicolor &>/dev/null
    /usr/bin/gtk-update-icon-cache %{_datadir}/icons/hicolor &>/dev/null || :
fi

%posttrans
/usr/bin/gtk-update-icon-cache %{_datadir}/icons/hicolor &>/dev/null || :

%files
%{_pkgdocdir}/AUTHORS
%{_pkgdocdir}/BUGS
%{_pkgdocdir}/ChangeLog
%{_pkgdocdir}/NEWS
%{_pkgdocdir}/README
%config(noreplace) %{_sysconfdir}/ld.so.conf.d/octave-*.conf
%{_bindir}/octave*
%{_libdir}/octave/
%{_libexecdir}/octave/
%{_mandir}/man1/octave*.1.*
%{_infodir}/liboctave.info*
%{_infodir}/octave.info*
%{_datadir}/appdata/www.octave.org-octave.appdata.xml
%{_datadir}/applications/www.octave.org-octave.desktop
%{_datadir}/icons/hicolor/*/apps/octave.png
%{_datadir}/icons/hicolor/scalable/apps/octave.svg
%dir %{_datadir}/octave
%{_datadir}/octave/%{version}/
%{_datadir}/octave/ls-R
%ghost %{_datadir}/octave/octave_packages
%{_datadir}/octave/packages/
%{_datadir}/octave/site/

%files devel
%{_rpmconfigdir}/macros.d/macros.octave
%{_bindir}/mkoctfile
%{_bindir}/mkoctfile-%{version}
%{_includedir}/octave-%{version}/
%{_mandir}/man1/mkoctfile.1.*

%files doc
%{_pkgdocdir}/examples/
%{_pkgdocdir}/liboctave.html/
%{_pkgdocdir}/octave.html
%{_pkgdocdir}/refcard*.pdf
%{_pkgdocdir}/octave.pdf
%{_pkgdocdir}/liboctave.pdf

%changelog
* Mon Aug 03 2015 Cjacker <cjacker@foxmail.com>
- initial build.
