
%define libname libtidy

%define snap 20091203

Name:    tidy
Summary: Utility to clean up and pretty print HTML/XHTML/XML
Version: 0.99.0
Release: 35.%{snap}%{?dist}

License: W3C
URL:     http://tidy.sourceforge.net/

Source0: tidy-%{snap}cvs.tar.gz
Source1: tab2space.1
Source10: tidy-cvs_checkout.sh

Patch0: tidy-20091203cvs-format.patch

BuildRequires: libtool
BuildRequires: doxygen
BuildRequires: libxslt

Requires: %{libname}%{?_isa} = %{version}-%{release}

%description
When editing HTML it's easy to make mistakes. Wouldn't it be nice if
there was a simple way to fix these mistakes automatically and tidy up
sloppy editing into nicely layed out markup? Well now there is! Dave
Raggett's HTML TIDY is a free utility for doing just that. It also
works great on the atrociously hard to read markup generated by
specialized HTML editors and conversion tools, and can help you
identify where you need to pay further attention on making your pages
more accessible to people with disabilities.

%package -n %{libname}
Summary: Shared libraries for %{name}
%description -n %{libname}
%{summary}.

%package -n %{libname}-devel
Summary: Development files for %{name}
Provides:  tidy-devel = %{version}-%{release}
Requires: %{libname}%{?_isa} = %{version}-%{release}

%description -n %{libname}-devel
%{summary}.


%prep
%setup -q -n %{name}
%patch0 -p1 -b .format

# htmldocs included in cvs checkout
#setup -q -n %{name} -T -D -b1

sh build/gnuauto/setup.sh


%build
%configure \
  --disable-static \
  --disable-dependency-tracking

make %{?_smp_mflags}

# api docs
doxygen htmldoc/doxygen.cfg

# make doc steps gleaned from build/gmake/Makefile
pushd htmldoc
../console/tidy -xml-config > tidy-config.xml
../console/tidy -xml-help   > tidy-help.xml
xsltproc -o tidy.1 tidy1.xsl tidy-help.xml
xsltproc -o quickref.html quickref-html.xsl tidy-config.xml
popd


%install
rm -rf $RPM_BUILD_ROOT

make install DESTDIR=$RPM_BUILD_ROOT

install -p -m644 -D htmldoc/tidy.1 $RPM_BUILD_ROOT%{_mandir}/man1/tidy.1
install -p -m644  %{SOURCE1} $RPM_BUILD_ROOT%{_mandir}/man1/

## Unpackaged files
rm -f $RPM_BUILD_ROOT%{_libdir}/lib*.la


%clean
rm -rf $RPM_BUILD_ROOT

%check
cp test/testone.sh{,~}
sed -i 's|TIDY=../bin/tidy|TIDY=../console/tidy|' test/testone.sh
cd test
./testall.sh
mv testone.sh{~,}

%post -n %{libname} -p /sbin/ldconfig

%postun -n %{libname} -p /sbin/ldconfig


%files
%defattr(-,root,root,-)
%doc htmldoc/*.html htmldoc/*.css htmldoc/*.gif
%{_bindir}/tab2space
%{_bindir}/tidy
%{_mandir}/man1/tidy.1*
%{_mandir}/man1/tab2space.1*

%files -n %{libname}
%defattr(-,root,root,-)
%{_libdir}/libtidy-0.99.so.0*

%files -n %{libname}-devel
%defattr(-,root,root,-)
%doc htmldoc/api/*
%{_includedir}/*.h
%{_libdir}/libtidy.so


%changelog
* Wed Oct 28 2015 Cjacker <cjacker@foxmail.com> - 0.99.0-35.20091203
- Initial build

