%global        debug_package %{nil}

Name: drbl
Version: 2.11.15
Release: 2
License: GPL
Summary:Diskless Remote Boot in Linux: manage the deployment of the GNU/Linux operating system across many clients

Source0: drbl-2.11.15.tar.bz2
Patch0: usrbin.patch
BuildRequires: vim perl-devel bc 
Requires: perl bc

%description
Diskless Remote Boot in Linux: manage the deployment of the GNU/Linux operating system across many clients

%prep
%setup -q -T -c -n drbl -b0 
cd %{_builddir}/%{name}/%{name}-%{version}
%patch0 -p0 

%build 
backup=(etc/drbl/drbl.conf)

cd %{_builddir}/%{name}/drbl-2.11.15
make 

%install
cd %{name}-%{version}
make DESTDIR=%{buildroot} install

%files
%{_sysconfdir}/drbl/client-append-fstab.example
%{_sysconfdir}/drbl/client-extra-service.example
%{_sysconfdir}/drbl/client-ip-hostname.example
%{_sysconfdir}/drbl/dcsrc.example
%{_sysconfdir}/drbl/drbl.conf
%{_bindir}/Forcevideo-drbl-live
%{_bindir}/dcs
%{_bindir}/drbl-3n-conf
%{_bindir}/drbl-all-service
%{_bindir}/drbl-aoe-img-dump
%{_bindir}/drbl-aoe-serv
%{_bindir}/drbl-autologin-env-reset
%{_bindir}/drbl-autologin-home-reset
%{_bindir}/drbl-bug-report
%{_bindir}/drbl-clean-autologin-account
%{_bindir}/drbl-clean-dhcpd-leases
%{_bindir}/drbl-client-reautologin
%{_bindir}/drbl-client-root-passwd
%{_bindir}/drbl-client-service
%{_bindir}/drbl-client-switch
%{_bindir}/drbl-client-system-select
%{_bindir}/drbl-collect-mac
%{_bindir}/drbl-cp
%{_bindir}/drbl-cp-host
%{_bindir}/drbl-cp-user
%{_bindir}/drbl-doit
%{_bindir}/drbl-fuh
%{_bindir}/drbl-fuh-get
%{_bindir}/drbl-fuh-put
%{_bindir}/drbl-fuh-rm
%{_bindir}/drbl-fuu
%{_bindir}/drbl-fuu-get
%{_bindir}/drbl-fuu-put
%{_bindir}/drbl-fuu-rm
%{_bindir}/drbl-get-host
%{_bindir}/drbl-get-user
%{_bindir}/drbl-host-cp
%{_bindir}/drbl-host-get
%{_bindir}/drbl-host-rm
%{_bindir}/drbl-live
%{_bindir}/drbl-live-boinc
%{_bindir}/drbl-live-hadoop
%{_bindir}/drbl-login-switch
%{_bindir}/drbl-netinstall
%{_bindir}/drbl-pxelinux-passwd
%{_bindir}/drbl-rm-host
%{_bindir}/drbl-rm-user
%{_bindir}/drbl-run-parts
%{_bindir}/drbl-sl
%{_bindir}/drbl-swapfile
%{_bindir}/drbl-syslinux-netinstall
%{_bindir}/drbl-user-cp
%{_bindir}/drbl-user-env-reset
%{_bindir}/drbl-user-get
%{_bindir}/drbl-user-rm
%{_bindir}/drbl-useradd
%{_bindir}/drbl-useradd-file
%{_bindir}/drbl-useradd-list
%{_bindir}/drbl-useradd-range
%{_bindir}/drbl-userdel
%{_bindir}/drbl-userdel-file
%{_bindir}/drbl-userdel-list
%{_bindir}/drbl-userdel-range
%{_bindir}/drbl-wakeonlan
%{_bindir}/drbl4imp
%{_bindir}/drblpush
%{_bindir}/drblsrv
%{_bindir}/drblsrv-offline
%{_bindir}/generate-pxe-menu
%{_bindir}/get-drbl-conf-param
%{_bindir}/mknic-nbi
%{_datadir}/drbl/bin/drbl-check-dm
%{_datadir}/drbl/bin/drbl-check-kernel-cpu-arch
%{_datadir}/drbl/bin/drbl-detect-cdrom
%{_datadir}/drbl/bin/drbl-get-common-username
%{_datadir}/drbl/bin/drbl-get-ipadd
%{_datadir}/drbl/bin/drbl-get-macadd
%{_datadir}/drbl/bin/drbl-get-netmask
%{_datadir}/drbl/bin/drbl-get-network
%{_datadir}/drbl/bin/drbl-get-nfsserver
%{_datadir}/drbl/bin/drbl-gethostip
%{_datadir}/drbl/bin/drbl-ipcalc
%{_datadir}/drbl/bin/drbl-ipcalc-list
%{_datadir}/drbl/bin/drbl-langchooser
%{_datadir}/drbl/bin/drbl-sha1pass
%{_datadir}/drbl/bin/drbl-tune-pxecfg-block
%{_datadir}/drbl/bin/drbl-website
%{_datadir}/drbl/bin/find-url-in-rpm-md-set
%{_datadir}/drbl/bin/find-url-in-yum-set
%{_datadir}/drbl/bin/fqdn-etc-host.sh
%{_datadir}/drbl/bin/get-all-nic-ip
%{_datadir}/drbl/bin/get-assigned-hn-by-ip
%{_datadir}/drbl/bin/get-client-ip-list
%{_datadir}/drbl/bin/get-ip-link-2-drbl-srv
%{_datadir}/drbl/bin/get-necessary-nfsd-no
%{_datadir}/drbl/bin/get-nic-devs
%{_datadir}/drbl/bin/get-port-link-2-drbl-srv
%{_datadir}/drbl/bin/get-rpm-list-from-yum
%{_datadir}/drbl/bin/hide_reveal_pxe_img
%{_datadir}/drbl/bin/list_available_deb
%{_datadir}/drbl/bin/list_available_rpm
%{_datadir}/drbl/bin/list_available_tarball
%{_datadir}/drbl/bin/list_latest_deb
%{_datadir}/drbl/bin/list_latest_rpm
%{_datadir}/drbl/bin/list_latest_tarball
%{_datadir}/drbl/bin/parse_apt_url_get_rpm.sh
%{_datadir}/drbl/bin/parse_dhcpd_conf
%{_datadir}/drbl/bin/parse_net_conf
%{_datadir}/drbl/bin/pkg-ver-latest
%{_datadir}/drbl/doc/AUTHORS
%{_datadir}/drbl/doc/ChangeLog.txt
%{_datadir}/drbl/doc/GPL
%{_datadir}/drbl/doc/Known_issues.txt
%{_datadir}/drbl/doc/Known_issues_Big5.txt
%{_datadir}/drbl/doc/README
%{_datadir}/drbl/doc/RELEASE-NOTES
%{_datadir}/drbl/doc/VERSION
%{_datadir}/drbl/image/drbllogo.png
%{_datadir}/drbl/image/drblwp.png
%{_datadir}/drbl/image/ocslogo.png
%{_datadir}/drbl/image/ocswp-grub2.png
%{_datadir}/drbl/image/ocswp.png
%{_datadir}/drbl/image/ocswp.xpm.gz
%{_datadir}/drbl/lang/bash/ca_ES
%{_datadir}/drbl/lang/bash/ca_ES.UTF-8
%{_datadir}/drbl/lang/bash/check-bash-lang
%{_datadir}/drbl/lang/bash/de_DE
%{_datadir}/drbl/lang/bash/de_DE.UTF-8
%{_datadir}/drbl/lang/bash/en_US
%{_datadir}/drbl/lang/bash/en_US.UTF-8
%{_datadir}/drbl/lang/bash/es_ES
%{_datadir}/drbl/lang/bash/es_ES.UTF-8
%{_datadir}/drbl/lang/bash/fr_FR
%{_datadir}/drbl/lang/bash/fr_FR.UTF-8
%{_datadir}/drbl/lang/bash/it_IT
%{_datadir}/drbl/lang/bash/it_IT.UTF-8
%{_datadir}/drbl/lang/bash/ja_JP.UTF-8
%{_datadir}/drbl/lang/bash/pt_BR
%{_datadir}/drbl/lang/bash/pt_BR.UTF-8
%{_datadir}/drbl/lang/bash/ru_RU.UTF-8
%{_datadir}/drbl/lang/bash/sk_SK
%{_datadir}/drbl/lang/bash/sk_SK.UTF-8
%{_datadir}/drbl/lang/bash/tr_TR
%{_datadir}/drbl/lang/bash/tr_TR.UTF-8
%{_datadir}/drbl/lang/bash/zh_CN.UTF-8
%{_datadir}/drbl/lang/bash/zh_TW.UTF-8
%{_datadir}/drbl/lang/perl/ca_ES
%{_datadir}/drbl/lang/perl/ca_ES.UTF-8
%{_datadir}/drbl/lang/perl/check-perl-lang
%{_datadir}/drbl/lang/perl/de_DE
%{_datadir}/drbl/lang/perl/de_DE.UTF-8
%{_datadir}/drbl/lang/perl/en_US
%{_datadir}/drbl/lang/perl/en_US.UTF-8
%{_datadir}/drbl/lang/perl/es_ES
%{_datadir}/drbl/lang/perl/es_ES.UTF-8
%{_datadir}/drbl/lang/perl/fr_FR
%{_datadir}/drbl/lang/perl/fr_FR.UTF-8
%{_datadir}/drbl/lang/perl/it_IT
%{_datadir}/drbl/lang/perl/it_IT.UTF-8
%{_datadir}/drbl/lang/perl/ja_JP.UTF-8
%{_datadir}/drbl/lang/perl/pt_BR
%{_datadir}/drbl/lang/perl/pt_BR.UTF-8
%{_datadir}/drbl/lang/perl/ru_RU.UTF-8
%{_datadir}/drbl/lang/perl/sk_SK
%{_datadir}/drbl/lang/perl/sk_SK.UTF-8
%{_datadir}/drbl/lang/perl/tr_TR
%{_datadir}/drbl/lang/perl/tr_TR.UTF-8
%{_datadir}/drbl/lang/perl/zh_CN.UTF-8
%{_datadir}/drbl/lang/perl/zh_TW.UTF-8
%{_datadir}/drbl/pkg/memtest86+/README
%{_datadir}/drbl/pkg/syslinux/README
%{_datadir}/drbl/pkg/syslinux/makeboot.bat
%{_datadir}/drbl/pkg/syslinux/makeboot.sh
%{_datadir}/drbl/pkg/syslinux/makeboot64.bat
%{_datadir}/drbl/pki/rpm-gpg/RPM-GPG-KEY-DRBL
%{_datadir}/drbl/postrun/drbl/00-readme.txt
%{_datadir}/drbl/prerun/drbl/00-readme.txt
%{_datadir}/drbl/sbin/check_drbl_setup_space
%{_datadir}/drbl/sbin/deb-preconf-drbl
%{_datadir}/drbl/sbin/drbl-client-xfs-switch
%{_datadir}/drbl/sbin/drbl-conf-functions
%{_datadir}/drbl/sbin/drbl-etc-hosts
%{_datadir}/drbl/sbin/drbl-functions
%{_datadir}/drbl/sbin/drbl-gen-client-files
%{_datadir}/drbl/sbin/drbl-gen-pxe-nbi
%{_datadir}/drbl/sbin/drbl-gen-ssh-host-keys
%{_datadir}/drbl/sbin/drbl-gen-ssi-files
%{_datadir}/drbl/sbin/drbl-kbdchooser
%{_datadir}/drbl/sbin/drbl-live-conf-X
%{_datadir}/drbl/sbin/drbl-nat-rules
%{_datadir}/drbl/sbin/drbl-nfs-conf
%{_datadir}/drbl/sbin/drbl-nfs-exports
%{_datadir}/drbl/sbin/drbl-perl-functions
%{_datadir}/drbl/sbin/drbl-powerful-thin-client
%{_datadir}/drbl/sbin/drbl-prepare-memtest
%{_datadir}/drbl/sbin/drbl-prepare-pxelinux
%{_datadir}/drbl/sbin/drbl-ssi-client-prepare
%{_datadir}/drbl/sbin/drbl-yp-securenets
%{_datadir}/drbl/sbin/install-kernel-for-client
%{_datadir}/drbl/sbin/prepare-files-for-PXE-client
%{_datadir}/drbl/sbin/select-drbl-clients
%{_datadir}/drbl/sbin/set-default-pxe-img
%{_datadir}/drbl/sbin/switch-pxe-bg-mode
%{_datadir}/drbl/sbin/switch-pxe-menu
%{_datadir}/drbl/sbin/tune-clientdir-opt
%{_datadir}/drbl/sbin/tune-debian-dev-group-perm
%{_datadir}/drbl/sbin/update-drbl-client-kernel-from-server
%{_datadir}/drbl/setup/files/DBN/DBN-TU/firstboot.DBN-TU.drbl
%{_datadir}/drbl/setup/files/DBN/DBN5.0.1/firstboot.DBN5.0.1.drbl
%{_datadir}/drbl/setup/files/DBN/DBN5.0.2/firstboot.DBN5.0.2.drbl
%{_datadir}/drbl/setup/files/DBN/DBN5.0.3/firstboot.DBN5.0.3.drbl
%{_datadir}/drbl/setup/files/DBN/DBN5.0.4/firstboot.DBN5.0.4.drbl
%{_datadir}/drbl/setup/files/DBN/DBN5.0.8/firstboot.DBN5.0.8.drbl
%{_datadir}/drbl/setup/files/DBN/DBN5.0/firstboot.DBN5.0.drbl
%{_datadir}/drbl/setup/files/DBN/DBN6.0.1/firstboot.DBN6.0.1.drbl
%{_datadir}/drbl/setup/files/DBN/DBN6.0.2/firstboot.DBN6.0.2.drbl
%{_datadir}/drbl/setup/files/DBN/DBN6.0.3/firstboot.DBN6.0.3.drbl
%{_datadir}/drbl/setup/files/DBN/DBN6.0.4/firstboot.DBN6.0.4.drbl
%{_datadir}/drbl/setup/files/DBN/DBN6.0.5/firstboot.DBN6.0.5.drbl
%{_datadir}/drbl/setup/files/DBN/DBN6.0.6/firstboot.DBN6.0.6.drbl
%{_datadir}/drbl/setup/files/DBN/DBN6.0.7/firstboot.DBN6.0.7.drbl
%{_datadir}/drbl/setup/files/DBN/DBN6.0/firstboot.DBN6.0.drbl
%{_datadir}/drbl/setup/files/DBN/DBN7.0/firstboot.DBN7.0.drbl
%{_datadir}/drbl/setup/files/DBN/DBN7.1/firstboot.DBN7.1.drbl
%{_datadir}/drbl/setup/files/DBN/DBN7.2/firstboot.DBN7.2.drbl
%{_datadir}/drbl/setup/files/DBN/DBN7.3/firstboot.DBN7.3.drbl
%{_datadir}/drbl/setup/files/DBN/DBN7.4/firstboot.DBN7.4.drbl
%{_datadir}/drbl/setup/files/DBN/DBN7.5/firstboot.DBN7.5.drbl
%{_datadir}/drbl/setup/files/DBN/DBN7.6/firstboot.DBN7.6.drbl
%{_datadir}/drbl/setup/files/DBN/DBN7.7/firstboot.DBN7.7.drbl
%{_datadir}/drbl/setup/files/DBN/firstboot.default-DBN.drbl
%{_datadir}/drbl/setup/files/RH/CO5.0/halt.CO5.0.drbl
%{_datadir}/drbl/setup/files/RH/CO5.0/halt.CO5.0.original
%{_datadir}/drbl/setup/files/RH/CO5.0/rc.sysinit.CO5.0.drbl
%{_datadir}/drbl/setup/files/RH/CO5.0/rc.sysinit.CO5.0.original
%{_datadir}/drbl/setup/files/RH/CO5.1/halt.CO5.1.drbl
%{_datadir}/drbl/setup/files/RH/CO5.1/halt.CO5.1.original
%{_datadir}/drbl/setup/files/RH/CO5.1/rc.sysinit.CO5.1.drbl
%{_datadir}/drbl/setup/files/RH/CO5.1/rc.sysinit.CO5.1.original
%{_datadir}/drbl/setup/files/RH/CO5.10/halt.CO5.10.drbl
%{_datadir}/drbl/setup/files/RH/CO5.10/halt.CO5.10.original
%{_datadir}/drbl/setup/files/RH/CO5.10/rc.sysinit.CO5.10.drbl
%{_datadir}/drbl/setup/files/RH/CO5.10/rc.sysinit.CO5.10.original
%{_datadir}/drbl/setup/files/RH/CO5.2/halt.CO5.2.drbl
%{_datadir}/drbl/setup/files/RH/CO5.2/halt.CO5.2.original
%{_datadir}/drbl/setup/files/RH/CO5.2/rc.sysinit.CO5.2.drbl
%{_datadir}/drbl/setup/files/RH/CO5.2/rc.sysinit.CO5.2.original
%{_datadir}/drbl/setup/files/RH/CO5.3/halt.CO5.3.drbl
%{_datadir}/drbl/setup/files/RH/CO5.3/halt.CO5.3.original
%{_datadir}/drbl/setup/files/RH/CO5.3/rc.sysinit.CO5.3.drbl
%{_datadir}/drbl/setup/files/RH/CO5.3/rc.sysinit.CO5.3.original
%{_datadir}/drbl/setup/files/RH/CO5.4/halt.CO5.4.drbl
%{_datadir}/drbl/setup/files/RH/CO5.4/halt.CO5.4.original
%{_datadir}/drbl/setup/files/RH/CO5.4/rc.sysinit.CO5.4.drbl
%{_datadir}/drbl/setup/files/RH/CO5.4/rc.sysinit.CO5.4.original
%{_datadir}/drbl/setup/files/RH/CO5.5/halt.CO5.5.drbl
%{_datadir}/drbl/setup/files/RH/CO5.5/halt.CO5.5.original
%{_datadir}/drbl/setup/files/RH/CO5.5/rc.sysinit.CO5.5.drbl
%{_datadir}/drbl/setup/files/RH/CO5.5/rc.sysinit.CO5.5.original
%{_datadir}/drbl/setup/files/RH/CO5.6/halt.CO5.6.drbl
%{_datadir}/drbl/setup/files/RH/CO5.6/halt.CO5.6.original
%{_datadir}/drbl/setup/files/RH/CO5.6/rc.sysinit.CO5.6.drbl
%{_datadir}/drbl/setup/files/RH/CO5.6/rc.sysinit.CO5.6.original
%{_datadir}/drbl/setup/files/RH/CO5.7/halt.CO5.7.drbl
%{_datadir}/drbl/setup/files/RH/CO5.7/halt.CO5.7.original
%{_datadir}/drbl/setup/files/RH/CO5.7/rc.sysinit.CO5.7.drbl
%{_datadir}/drbl/setup/files/RH/CO5.7/rc.sysinit.CO5.7.original
%{_datadir}/drbl/setup/files/RH/CO5.8/halt.CO5.8.drbl
%{_datadir}/drbl/setup/files/RH/CO5.8/halt.CO5.8.original
%{_datadir}/drbl/setup/files/RH/CO5.8/rc.sysinit.CO5.8.drbl
%{_datadir}/drbl/setup/files/RH/CO5.8/rc.sysinit.CO5.8.original
%{_datadir}/drbl/setup/files/RH/CO5.9/halt.CO5.9.drbl
%{_datadir}/drbl/setup/files/RH/CO5.9/halt.CO5.9.original
%{_datadir}/drbl/setup/files/RH/CO5.9/rc.sysinit.CO5.9.drbl
%{_datadir}/drbl/setup/files/RH/CO5.9/rc.sysinit.CO5.9.original
%{_datadir}/drbl/setup/files/RH/CO5/halt.CO5.drbl
%{_datadir}/drbl/setup/files/RH/CO5/halt.CO5.original
%{_datadir}/drbl/setup/files/RH/CO5/rc.sysinit.CO5.drbl
%{_datadir}/drbl/setup/files/RH/CO5/rc.sysinit.CO5.original
%{_datadir}/drbl/setup/files/RH/CO6.0/halt.CO6.0.drbl
%{_datadir}/drbl/setup/files/RH/CO6.0/halt.CO6.0.original
%{_datadir}/drbl/setup/files/RH/CO6.0/rc.sysinit.CO6.0.drbl
%{_datadir}/drbl/setup/files/RH/CO6.0/rc.sysinit.CO6.0.original
%{_datadir}/drbl/setup/files/RH/CO6.1/halt.CO6.1.drbl
%{_datadir}/drbl/setup/files/RH/CO6.1/halt.CO6.1.original
%{_datadir}/drbl/setup/files/RH/CO6.1/rc.sysinit.CO6.1.drbl
%{_datadir}/drbl/setup/files/RH/CO6.1/rc.sysinit.CO6.1.original
%{_datadir}/drbl/setup/files/RH/CO6.2/halt.CO6.2.drbl
%{_datadir}/drbl/setup/files/RH/CO6.2/halt.CO6.2.original
%{_datadir}/drbl/setup/files/RH/CO6.2/rc.sysinit.CO6.2.drbl
%{_datadir}/drbl/setup/files/RH/CO6.2/rc.sysinit.CO6.2.original
%{_datadir}/drbl/setup/files/RH/CO6.3/halt.CO6.3.drbl
%{_datadir}/drbl/setup/files/RH/CO6.3/halt.CO6.3.original
%{_datadir}/drbl/setup/files/RH/CO6.3/rc.sysinit.CO6.3.drbl
%{_datadir}/drbl/setup/files/RH/CO6.3/rc.sysinit.CO6.3.original
%{_datadir}/drbl/setup/files/RH/CO6.4/halt.CO6.4.drbl
%{_datadir}/drbl/setup/files/RH/CO6.4/halt.CO6.4.original
%{_datadir}/drbl/setup/files/RH/CO6.4/rc.sysinit.CO6.4.drbl
%{_datadir}/drbl/setup/files/RH/CO6.4/rc.sysinit.CO6.4.original
%{_datadir}/drbl/setup/files/RH/CO6.5/halt.CO6.5.drbl
%{_datadir}/drbl/setup/files/RH/CO6.5/halt.CO6.5.original
%{_datadir}/drbl/setup/files/RH/CO6.5/rc.sysinit.CO6.5.drbl
%{_datadir}/drbl/setup/files/RH/CO6.5/rc.sysinit.CO6.5.original
%{_datadir}/drbl/setup/files/RH/CO6.6/halt.CO6.6.drbl
%{_datadir}/drbl/setup/files/RH/CO6.6/halt.CO6.6.original
%{_datadir}/drbl/setup/files/RH/CO6.6/rc.sysinit.CO6.6.drbl
%{_datadir}/drbl/setup/files/RH/CO6.6/rc.sysinit.CO6.6.original
%{_datadir}/drbl/setup/files/RH/CO7.0.1406/systemd/system/ocsd-rescue.service
%{_datadir}/drbl/setup/files/RH/CO7.0.1406/systemd/system/ocsd-run.service
%{_datadir}/drbl/setup/files/RH/CO7/systemd/system/ocsd-rescue.service
%{_datadir}/drbl/setup/files/RH/CO7/systemd/system/ocsd-run.service
%{_datadir}/drbl/setup/files/RH/FC14/halt.FC14.drbl
%{_datadir}/drbl/setup/files/RH/FC14/halt.FC14.original
%{_datadir}/drbl/setup/files/RH/FC14/rc.sysinit.FC14.drbl
%{_datadir}/drbl/setup/files/RH/FC14/rc.sysinit.FC14.original
%{_datadir}/drbl/setup/files/RH/FC17/systemd/system/ocsd-rescue.service
%{_datadir}/drbl/setup/files/RH/FC17/systemd/system/ocsd-run.service
%{_datadir}/drbl/setup/files/RH/FC18/systemd/system/ocsd-rescue.service
%{_datadir}/drbl/setup/files/RH/FC18/systemd/system/ocsd-run.service
%{_datadir}/drbl/setup/files/RH/FC20/systemd/system/ocsd-rescue.service
%{_datadir}/drbl/setup/files/RH/FC20/systemd/system/ocsd-run.service
%{_datadir}/drbl/setup/files/RH/halt.default-RH.drbl
%{_datadir}/drbl/setup/files/RH/rc.sysinit.default-RH.drbl
%{_datadir}/drbl/setup/files/RH/single.drbl
%{_datadir}/drbl/setup/files/SUSE/SUSE11.0/firstboot.SUSE11.0.drbl
%{_datadir}/drbl/setup/files/SUSE/SUSE11.1/firstboot.SUSE11.1.drbl
%{_datadir}/drbl/setup/files/SUSE/SUSE11.2/firstboot.SUSE11.2.drbl
%{_datadir}/drbl/setup/files/SUSE/SUSE11.3/firstboot.SUSE11.3.drbl
%{_datadir}/drbl/setup/files/SUSE/SUSE11.4/firstboot.SUSE11.4.drbl
%{_datadir}/drbl/setup/files/SUSE/firstboot.default-SUSE.drbl
%{_datadir}/drbl/setup/files/Ubuntu/12.04/S00wait-drbl
%{_datadir}/drbl/setup/files/Ubuntu/12.04/drbl-client-boot.conf
%{_datadir}/drbl/setup/files/Ubuntu/12.04/plymouth.conf
%{_datadir}/drbl/setup/files/Ubuntu/12.10/S00wait-drbl
%{_datadir}/drbl/setup/files/Ubuntu/12.10/drbl-client-boot.conf
%{_datadir}/drbl/setup/files/Ubuntu/13.04/S00wait-drbl
%{_datadir}/drbl/setup/files/Ubuntu/13.04/drbl-client-boot.conf
%{_datadir}/drbl/setup/files/Ubuntu/13.10/S00wait-drbl
%{_datadir}/drbl/setup/files/Ubuntu/13.10/drbl-client-boot.conf
%{_datadir}/drbl/setup/files/Ubuntu/14.04/S00wait-drbl
%{_datadir}/drbl/setup/files/Ubuntu/14.04/drbl-client-boot.conf
%{_datadir}/drbl/setup/files/Ubuntu/14.10/S00wait-drbl
%{_datadir}/drbl/setup/files/Ubuntu/14.10/drbl-client-boot.conf
%{_datadir}/drbl/setup/files/Ubuntu/S00wait-drbl-default
%{_datadir}/drbl/setup/files/Ubuntu/drbl-client-boot-default.conf
%{_datadir}/drbl/setup/files/boinc/S99run-boinc
%{_datadir}/drbl/setup/files/boinc/conf/drbl-boinc.conf
%{_datadir}/drbl/setup/files/boinc/run-as-user
%{_datadir}/drbl/setup/files/boinc/template/account_www.worldcommunitygrid.org.xml.template
%{_datadir}/drbl/setup/files/boinc/template/ca-bundle.crt
%{_datadir}/drbl/setup/files/boinc/template/global_prefs.xml.template
%{_datadir}/drbl/setup/files/misc/arm-wol
%{_datadir}/drbl/setup/files/misc/desktop-icons/drbl-live/Clonezilla-live.desktop
%{_datadir}/drbl/setup/files/misc/desktop-icons/drbl-live/Clonezilla-server.desktop
%{_datadir}/drbl/setup/files/misc/desktop-icons/drbl-live/Display.desktop
%{_datadir}/drbl/setup/files/misc/desktop-icons/drbl-live/GParted.desktop
%{_datadir}/drbl/setup/files/misc/desktop-icons/drbl-live/Start_DRBL.desktop
%{_datadir}/drbl/setup/files/misc/desktop-icons/drbl-live/Stop_DRBL.desktop
%{_datadir}/drbl/setup/files/misc/drbl-clients-nat
%{_datadir}/drbl/setup/files/misc/drblthincli
%{_datadir}/drbl/setup/files/misc/force-load-ide
%{_datadir}/drbl/setup/files/misc/gdm-safe-restart
%{_datadir}/drbl/setup/files/misc/init.drbl
%{_datadir}/drbl/setup/files/misc/mkswapfile
%{_datadir}/drbl/setup/files/misc/networking
%{_datadir}/drbl/setup/files/misc/parse-load-mod-suse
%{_datadir}/drbl/setup/files/misc/setupx_redhat.tgz
%{_datadir}/drbl/setup/files/misc/start-srv-after-ifup
%{_datadir}/drbl/setup/files/misc/start_udev.drbl
%{_datadir}/drbl/setup/rpm-md-repos/drbl-testing.repo
%{_datadir}/drbl/setup/rpm-md-repos/drbl-unstable.repo
%{_datadir}/drbl/setup/rpm-md-repos/drbl.repo
%{_datadir}/drbl/setup/yum-repos/drbl-extra.repo
%{_datadir}/drbl/setup/yum-repos/drbl-legacy.repo
%{_datadir}/drbl/setup/yum-repos/drbl-testing.repo
%{_datadir}/drbl/setup/yum-repos/drbl-unstable.repo
%{_datadir}/drbl/setup/yum-repos/drbl.repo
%{_datadir}/drbl/setup/yum-repos/opensuse-10.0.repo
%{_datadir}/drbl/setup/yum-repos/opensuse-10.1.repo
%{_datadir}/drbl/setup/yum-repos/opensuse-10.2.repo
%{_datadir}/drbl/setup/yum-repos/opensuse-10.3.repo
%{_datadir}/drbl/setup/yum-repos/opensuse-11.0.repo
%{_datadir}/drbl/setup/yum-repos/opensuse-updates-10.0.repo
%{_datadir}/drbl/setup/yum-repos/opensuse-updates-10.1.repo
%{_datadir}/drbl/setup/yum-repos/opensuse-updates-10.2.repo
%{_datadir}/drbl/setup/yum-repos/opensuse-updates-10.3.repo
%{_datadir}/drbl/setup/yum-repos/opensuse-updates-11.0.repo
%{_datadir}/gdm/themes/drbl-gdm/GdmGreeterTheme.desktop
%{_datadir}/gdm/themes/drbl-gdm/clonezilla/ocslogo-1.png
%{_datadir}/gdm/themes/drbl-gdm/clonezilla/ocslogo-2.png
%{_datadir}/gdm/themes/drbl-gdm/clonezilla/ocslogo-3-grub2.png
%{_datadir}/gdm/themes/drbl-gdm/clonezilla/ocslogo-3.png
%{_datadir}/gdm/themes/drbl-gdm/drbl-gdm.xml
%{_datadir}/gdm/themes/drbl-gdm/drbl.png
%{_datadir}/gdm/themes/drbl-gdm/language.png
%{_datadir}/gdm/themes/drbl-gdm/quit.png
%{_datadir}/gdm/themes/drbl-gdm/screenshot.png
%{_datadir}/gdm/themes/drbl-gdm/session.png
%{_datadir}/gdm/themes/drbl-gdm/system.png


%changelog
* Thu Dec 10 2015 kun.li@i-soft.com.cn - 2.11.15-2
- rebuilt

