%global _binfmtdir /usr/lib/binfmt.d
%global binfmt_apply() \
/usr/lib/systemd/systemd-binfmt  %{?*} >/dev/null 2>&1 || : \
%{nil}

Summary: An open source, cross-platform, implementation of C# and the CLR that is binary compatible with Microsoft.NET. 
Name:   mono
Version: 4.0.4.1
Release: 2 
License: GPLv2+
Source:  %{name}-%{version}.tar.bz2
Source1: mono.binfmt.d

# generated by running the following command:
# sn -k mono.snk
# You should not regenerate this unless you have a really, really, really good reason.
Source2:        mono.snk

Patch1: mono-fix-nunit-pkgconfig-version-path.patch

Patch2: mono-4.0.0-ignore-reference-assemblies.patch
#yes, build mono need mono.
#for bootstrap, use "--disable-mcs-build" to generate native codes.
#install all mcs related dll/exe from a pre-built package.
#and rebuild full mono codes.
BuildRequires: mono 
BuildRequires: libgdiplus
Requires: libgdiplus

%description
An open source, cross-platform, implementation of C# and the CLR that is binary compatible with Microsoft.NET

%package devel
Summary: Libraries and headers for %{name}
Requires: %name = %{version}

%description devel
Libraries and headers for %{name}

%prep
%setup -q -n mono-4.0.4
%patch1 -p1
#%patch2 -p1

# Add undeclared Arg
sed -i "61a #define ARG_MAX     _POSIX_ARG_MAX" mono/io-layer/wapi_glob.h

# Remove prebuilt binaries
#find . -name "*.dll" -not -path "./mcs/class/lib/monolite/*" -print -delete
#find . -name "*.exe" -not -path "./mcs/class/lib/monolite/*" -print -delete


%build
export CFLAGS="$RPM_OPT_FLAGS -fno-strict-aliasing"

%configure \
    --disable-static \
    --disable-quiet-build \
    --disable-system-aot

make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT
make install DESTDIR=$RPM_BUILD_ROOT

# copy the mono.snk key into /etc/pki/mono
mkdir -p %{buildroot}%{_sysconfdir}/pki/mono
install -p -m0644 %{SOURCE2} %{buildroot}%{_sysconfdir}/pki/mono/

# Remove hardcoded lib directory from the config
sed -i s,%{_prefix}/lib/,,g %{buildroot}%{_sysconfdir}/mono/config

# remove .la files (they are generally bad news)
rm -f %{buildroot}%{_libdir}/*.la

# remove Windows-only stuff
rm -rf %{buildroot}%{_prefix}/lib/mono/*/Mono.Security.Win32*
rm -f %{buildroot}%{_libdir}/libMonoSupportW.*

# remove libgc cruft
rm -rf %{buildroot}%{_datadir}/libgc-mono

# remove stuff that we don't package
rm -f %{buildroot}%{_bindir}/cilc
rm -f %{buildroot}%{_mandir}/man1/cilc.1*
rm -f %{buildroot}%{_prefix}/lib/mono/*/browsercaps-updater.exe*
rm -f %{buildroot}%{_prefix}/lib/mono/*/culevel.exe*

# Fix non-executable-in-bin
chmod +x %{buildroot}%{_bindir}/mono-gdb.py
chmod +x %{buildroot}%{_bindir}/mono-sgen-gdb.py

#ERROR: link target doesn't exist (neither in build root nor in installed system):
rm -rf %{buildroot}%{_prefix}/lib/mono/xbuild/12.0/bin/Microsoft.Build.dll
rm -rf %{buildroot}%{_prefix}/lib/mono/xbuild/12.0/bin/Microsoft.Build.Engine.dll
rm -rf %{buildroot}%{_prefix}/lib/mono/xbuild/12.0/bin/Mono.XBuild.Tasks.dll
rm -rf %{buildroot}%{_prefix}/lib/mono/xbuild/12.0/bin/Microsoft.Build.Framework.dll
rm -rf %{buildroot}%{_prefix}/lib/mono/xbuild/12.0/bin/Microsoft.Build.Tasks.v12.0.dll
rm -rf %{buildroot}%{_prefix}/lib/mono/xbuild/12.0/bin/Microsoft.Build.Utilities.v12.0.dll


rm -rf %{buildroot}/%{_libdir}/*.a

install -D -m644 %{SOURCE1} $RPM_BUILD_ROOT%{_binfmtdir}/mono.conf

sed -i -e "s:#Requires:Requires:" $RPM_BUILD_ROOT%{_libdir}/pkgconfig/mono.pc

%find_lang mcs

%clean
rm -rf $RPM_BUILD_ROOT

%post
%binfmt_apply mono.conf

%postun
if [ $1 -eq 0 ]; then
/bin/systemctl try-restart systemd-binfmt.service
fi

%files -f mcs.lang 
%defattr(-, root, root, -)
%{_sysconfdir}/pki/mono/
%dir %{_sysconfdir}/mono
%{_sysconfdir}/mono/*
%{_binfmtdir}/mono.conf
%{_bindir}/*
%{_libdir}/libMonoPosixHelper.so
#%{_libdir}/libMonoSupportW.so
%{_libdir}/libikvm-native.so
%{_libdir}/libmono*.so.*
%dir %{_libdir}/mono-source-libs
%{_libdir}/mono-source-libs/*
%dir %{_libdir}/mono
%{_libdir}/mono/*
%{_mandir}/man*/*.gz

%files devel
%defattr(-, root, root, -)
%dir %{_includedir}/mono-2.0
%{_includedir}/mono-2.0/*
%{_libdir}/libmono*.so
%dir %{_libdir}/monodoc
%{_libdir}/monodoc/*
%{_libdir}/pkgconfig/*.pc
%dir %{_datadir}/mono-2.0
%{_datadir}/mono-2.0/*


%changelog
* Tue Oct 27 2015 Cjacker <cjacker@foxmail.com> - 4.0.2.5-2
- Rebuild

